### ISSUE TITLE
Writing fixes

### ISSUE THREAD

**Issue by CarsonCummins11** [CarsonCummins11/AURA#28]
### **I'm sorry this will be really annoying but it has to happen**

Please refer students to the Greene Center for Career Education & Connections for resume and cover letter advice.
Please use the Oxford comma throughout to avoid confusion (e.g. backgrounds, majors or qualifications > backgrounds, majors, or qualifications)
“avoid using a “scattershot” strategy and applying…” > “avoid using a “scattershot” strategy by applying…”
“Research activities should be directly mentored by an experienced academic (professor, post-doctoral researcher or graduate student) who advise…” > “Research activities should be directly mentored by an experienced academic (professor, post-doctoral researcher, or graduate student) who advises…”
Change all the parenthetical “Here” links to undercase “here”
Add a period to “A list of internal funding opportunities for undergraduates is provided here”

In the “About” section: “...(AURA) is a platform that connects undergraduate students to research opportunities at the University of Rochester.” >> “...(AURA) is a platform that connects University of Rochester undergraduate students to research opportunities at the University.”
“Our Team”:  is it just the four students on the team??  Care to add more about yourselves, or not? Class year, major, LinkedIn contact??
Student FAQ, Q1: Capitalize the “R” in Office of Undergraduate Research”
Student FAQ, Q4: As Ann mentioned, direct them to Greene Center for resume help.
Student FAQ, Q5: “I would like to apply for a Discover grant”, >> “I would like to apply for a Discover Grant for Undergraduate Summer Research.”
Student FAQ, Q5: Capitalize the “G” in Discover Grant in the answer (2 places).
Professor FAQ, Q1: The answers should be noted as A, B, C, and D (not numerical) since they follow Q1 numbering.
Professor FAQ, Q2, Third sentence: Change the word “advise” to plural.  “(professor, post-doctoral researcher or graduate student) who advise the student” >> “(professor, post-doctoral researcher or graduate student) who advises the student”
Professor FAQ, Q3: “Yes, as long as the position can be characterized as “research” (see Q2 above), >> “Yes, as long as the position can be characterized as “research” (see Professor FAQ Q2 above),”  Refers to Q2 above but which Q2?  Either change the FAQ numbering to go from 1 to 15, or designate the “Q2 above” that you are referring to as the “Professor FAQ Q2”.
Professor FAQ, Q5: Same situation as above bullet.  “position needs to be a “research” opportunity (see Question 2).” Need to call out to which “Question 2” you are referring.
Professor FAQ, Q7, fourth sentence:  “successful applicant(s) using the process you described in your posting”   What are we referring to when we talk about the process they described in their posting?  Their timeline?
I think Sina & Ann mentioned changing Professor >> “Mentor” or “PI” - for the FAQ page as well.

Question 1 - Answer
Can we make “Office of Undergraduate Research” the URL link itself rather than having the link be “(Here)”
Question 2
Can we just shorten it to “Who can I contact for more information regarding a specific posting before I apply?”
Question 2 - Answer
“Please contact the email listed on the specific listing you have questions about”
Question 3
“The “Decision-By” date for a position I applied for has passed, but I have not received a reply. What should I do?”
Question 3 - Answer
“Please wait 3-5 business days before contacting the project mentor listed on the posting. They are very busy and are trying to get back to you as soon as they can. If they have not responded after 2 weeks after the Decision-By date has passed, contact the Office of Undergraduate Research (undergraduateresearch@ur.rochester.edu) and we will try to contact the PI on your behalf.” 
Question 4
Edit: “I need help with my résumé”
Question 4 - Answer
“Contact the Greene Center (career.center@rochester.edu) for help and advice for anything regarding your application process including interviews.”
Question 5 
Edit: Discover Grant, capital “G”
Edit: “Can I use my Discover Grant for a research position posted on AURA?”
Question 5 - Answer
“Yes! The Discover Grant can be used for all non-paid research projects. If you are interested in applying for a Discover Grant, please refer to the specific deadlines and application requirements listed here. Some sections of the application must be completed with or in-conjunction with your PI.”
Can the link be on the word “here,” no parentheses or capitalization 
Question 6
Edit: “postings” to “listings”
Question 6 - Answer
Yes, but we recommend that you avoid using a “scattershot” approach where you apply to all the listings in a certain discipline. You should identify and apply only to projects that are within your specific areas of interest in order to put together a more targeted and compelling application.”
Question 7 - Answer
“No, only University of Rochester undergraduates can apply for projects posted on AURA.”

**Comment by 1ForrestWargo1** [comment]
Have not  done these yet

Student FAQ, Q4: As Ann mentioned, direct them to Greene Center for resume help.

Professor FAQ, Q7, fourth sentence: “successful applicant(s) using the process you described in your posting” What are we referring to when we talk about the process they described in their posting? Their timeline?

**Comment by 1ForrestWargo1** [comment]
Also did not switch anything to oxford comma

**Comment by CarsonCummins11** [comment]
Honestly going to close this I don't think we need many more improvements. Thanks!
