### ISSUE TITLE
Add student application status tracker to projects

### ISSUE THREAD

**Issue by 1ForrestWargo1** [CarsonCummins11/AURA#39]

**Comment by CarsonCummins11** [comment]
What does this mean?

**Comment by 1ForrestWargo1** [comment]
Ghaemmaghami wanted information about the number of applicants that have been rejected and accepted

**Comment by CarsonCummins11** [comment]
I'm including showing that information in issue #34 I think - going to close this for now, and if you think that #34 is missing something would you mind just adding it? Thanks
