### ISSUE TITLE
Convert Expiration Emails to Cron jobs to prevent multiple emails sent due to UWSGI

### ISSUE THREAD

**Issue by CarsonCummins11** [CarsonCummins11/AURA#5]
Forrest's expiration email checking should be a system cronjob rather than running in the routes.py script to prevent UWSGI's multiple process model from sending multiple emails.

**Comment by CarsonCummins11** [comment]
This should also do the expiration itself - none of that is in the project currently

**Comment by CarsonCummins11** [comment]
Also (I can do this as well) setting the contacted property of every student on the project to true would be good to allow each student the opportunity to hit the "no email" button in their application tracker

**Comment by 1ForrestWargo1** [comment]
This should be good to go soon

**Comment by 1ForrestWargo1** [comment]
I am not running into the multiple instances problem - not sure if it happens on local host. There is an issue with sending the emails. It seems to be some problematic interaction with your email class.

**Comment by CarsonCummins11** [comment]
Ooooh okay yeah it definitely is - I switched from Yagmail to flask-mail to try and fix that issue originally (which it may or may not have). Switching back to yagmail will probably fix - I can fix and close out this issue if you want, or you can change it in the email class - just push the code you have so far!

**Comment by 1ForrestWargo1** [comment]
Hey sorry missed ur response. I have pushed the code - function expire project. I can switch it and/or find another solution

**Comment by 1ForrestWargo1** [comment]
back to yagmail - working on local
